# Generated by Django 3.2.25 on 2024-06-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degreeid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollmentYear',
        ),
    ]
