# Generated by Django 3.2.25 on 2024-06-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='classid',
            new_name='sectionID',
        ),
    ]
